name: Build APK

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Clean npm cache
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Login Expo
        run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build APK with EAS Cloud
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
